' Gambas module file

Public Sub Main()

    Dim ver As String = Application.Path
    Dim cofig As New Excfg
    Dim dbobj As New Exdb

    ' se especifica que conexcion se desea usar, es opcional y si no se hace el la primera funcional o la "default"
    dbobj.set = "default"
    ' si no se especifica que nombre/grupo de conexcion a db se usara la primera funcional o la default
    dbobj.db.Exec("select 'pepe' as ba")
    
    ' obtiene el nombre de dispositivo desde arbol udev
    Print exfile.getFileDev("/home/remoto")
    ' btiene el nombre del formato del sistema de ficheros
    Print exfile.getFileSys("/home/remoto")
    
    ' ejemplo de deteccion de rutas desde donde se realiza la invocacion pero no esta la app
    Print exapp.runbasepath
    ' ejemplo de deteccion de rutas desde donde esta la aplicacion que se esta invocando
    Print exapp.exebasepath
    ' ejemplo de deteccion de rutas desde donde esta todo lo de la applicacion
    Print exapp.parbasepath
    
    ver = exu.email("mail@domi.co")
    
    Print exu.email("mpes") & " y este " & ver
    
    Print exu.alphanumericlatin("apapapa@%$@") & "," & exu.alphanumericlatin(" apapapa") & "," & exu.alphanumericlatin("apapapa")
    
    Print "directorio " & exfile.getDirParent(Application.Path & "/.src") & " y busca " & exfile.getDirExist("/ekstra", User.Home &/ "Devel")
    
    Print exu.substr_count(" pepepep     adaadaasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj", "aa", gb.IgnoreCase)
    Print exu.ucfirst(" pepepep     adadasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj")
    Print exu.ucwords(" pepepep     adadasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj")
    Print exu.ucwords(" pepepep,adadasd,qoiehqopwiehoq aasa        aklsjbndka asada      asldaj", ",")
    Print exnet.gethttpbuf("http://google.com")
    
  exapp.ProcPid("firefox")

End
