' Gambas module file

Public Sub Main()

    Dim ver As String = Application.Path
    Dim cofig As New Excfg
    Dim dbobj As New Exdb
    
    dbobj["conex2"].Exec("select 'pepe' as ba")
    
    ' obtiene el nombre de dispositivo desde arbol udev
    Print exf.getFileDev("/")
    ' btiene el nombre del formato del sistema de ficheros
    Print exf.getFileSys("/")
    
    Print exapp.cf.cfgdb["conex0/hostname"]
    
    ' ejemplo de obtencion de configuracion
    Print cofig.cfgdb["conex0/hostname"]
    ' ejemplo de deteccion de rutas desde donde se realiza la invocacion pero no esta la app
    Print exapp.runbasepath
    ' ejemplo de deteccion de rutas desde donde esta la aplicacion que se esta invocando
    Print exapp.exebasepath
    
    ver = exu.email("mail@domi.co")
    
    Print exu.email("mpes") & " y este " & ver
    
    Print exu.alphanumericlatin("apapapa@%$@") & "," & exu.alphanumericlatin(" apapapa") & "," & exu.alphanumericlatin("apapapa")
    
    
    Print exu.substr_count(" pepepep     adaadaasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj", "aa", gb.IgnoreCase)
    Print exu.ucfirst(" pepepep     adadasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj")
    Print exu.ucwords(" pepepep     adadasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj")
    Print exu.ucwords(" pepepep,adadasd,qoiehqopwiehoq aasa        aklsjbndka asada      asldaj", ",")
    Print exu.gethttpbuf("http://google.com")
    
  exapp.ProcPid("firefox")

End
