' Gambas module file

Export

'' modulo de utilidades respecto el sistema de ficheros, requiere `libreoffice` para conversiones, `openoffice` solo para visor

Private commandshelltmp As String   '' variable interna para manejar el comando ejecutado en la rutina invocada
Private outputfunction As String    '' variable interna para resultado del comando ejecutado en la rutina invocada
Public _requisites As String = "awk,ifconfig,sh,bash,less,head,tail"


Public Sub caltoods(Optional namefile As String = "", Optional pathfile As String = "") As String '' exporta un archivo csv o excel a ods en donde se ejecute el modulo, @return: ruta de donde se guarda el resultado
  
  Dim entorno As String = "/tmp/LibreOffice_Conversion_" & User.Name

  If Comp(Replace(pathfile, " ", "", gb.IgnoreCase), "", gb.IgnoreCase) = 0 Then pathfile = "/tmp/"
  If Comp(Replace(namefile, " ", "", gb.IgnoreCase), "", gb.IgnoreCase) = 0 Then Return Null
  Try Kill pathfile &/ namefile
  commandshelltmp = "soffice -nodefault -nolockcheck -nologo -norestore -convert-to ods:\"OpenDocument Spreadsheet Flat XML\" -env:UserInstallation=file://" & entorno & " -headless -outdir " & pathfile & " " & namefile
  Shell commandshelltmp To outputfunction
  namefile = Mid(namefile, 1, RInStr(namefile, "."))
  namefile = Mid(namefile, RInStr(namefile, "/"), Len(namefile))
  If Exist(pathfile &/ namefile & "ods") Then Return pathfile &/ namefile & "ods"
  Return Null
  
End
