' Gambas module file


Public Function main()
    
    Print exModSysNet.getIfdef()
    Print exModSysNet.getIpall()[1]
    Print exModSysFile.getFileDev("/")
    Print exModSysFile.getFileSys("/")
    Print exModSysInfo.ProjInfo()
    Print exModUtil.ucfirst(" pepepep     adadasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj")
    Print exModUtil.ucwords(" pepepep     adadasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj")
    Print exModUtil.gethttpbuf("http://google.com")
    
End

