' Gambas module file


Public Function main()
    
    Print eMN.getIfdef()
    Print eMN.getIpall()[1]
    Print emf.getFileDev("/")
    Print emf.getFileSys("/")
    Print emi.ProjInfo()
    Print emu.substr_count(" pepepep     adaadaasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj", "aa", gb.IgnoreCase)
    Print emu.ucfirst(" pepepep     adadasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj")
    Print emu.ucwords(" pepepep     adadasd   qoiehqopwiehoq aasa        aklsjbndka asada      asldaj")
    Print emu.ucwords(" pepepep,adadasd,qoiehqopwiehoq aasa        aklsjbndka asada      asldaj", ",")
    Print emu.gethttpbuf("http://google.com")
    
End

