' Gambas module file


Private $datadesdedb As Connection[]
Private $configurado As Collection


Public Function main()
    
  Dim objconfs As New Ecfm
  Dim objdbcon As New Edbm

  $configurado = objconfs.configuracion
  Print "creacion/lectura archivo configuracion: " & objconfs.configurado
  $datadesdedb = objdbcon.conexciones
  Print "creacion/conesciones a bases de datos: " & objdbcon.conectados
    
End
