.TH "Gambas" "1" "March 2013" "User programs" "VenenuX GNU/Linux Development Environment"

.SH "NAME"
gambas3 \- Integrated Development Environment.

.SH "SYNOPSIS"
.B gambas3
<project file>

.B gambas3
<project directory>

.SH "DESCRIPTION"
Gambas is, before all, a Basic language with object extensions.
A program written with Gambas is a set of files. Each file describes
a class, in terms of object programming. The class files are compiled,
then executed by an interpreter. From this point of view, it is
very inspired by Java.

Gambas is made up of the following programs:

    * A compiler.
    * An interpreter.
    * An archiver.
    * A graphical user interface component.
    * A development environment.

The Gui IDE (Integrated Development Environment) is written with Gambas itself, so that I can
show the abilities of the language. And it is very useful for debugging!

\fBgambas3\fR starts the Integrated Development Environment.

The IDE offers: 
* A focused editor, with features such search&recplace, lookup funtions, sintax highlight
* Integrated designer for gui made components such forms or media objects usage.
* Per project management, with run inside and graphical debbuger.
* Build in tarball generadotr
* Integrated SQL interface for DB management interacting
* Debugger insterface for running test instances.

.SH "AVAILABILITY"
Updated source code and most documentation about gambas can be found at http://gambas.sf.net,
documentation about the language is at http://www.binara.com/gambas\-wiki,
documentation in the spanish language is at http://gambas.gnulinex.org.

.SH SEE ALSO

.TP
.B gambas3-ide(1)
.TP
.B gbi3(1)
.TP
.B gbc3(1)
.TP
.B gbs3(1)
.TP
.B gbx3(1)
.TP
.B gbw3(1)

.SH "REPORTING BUGS"
Report bugs to
<gambas@users.sourceforge.net>.

.SH "COPYRIGHT"
Copyright\(co 2002, 2013 \fBBenoit Minisini\fR \fI<gambas@users.sourceforge.net>\fR;
.PP
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "AUTHOR"
Gambas development environment was created and mantained by \fBBenoit Minisini\fR \fI<gambas@users.sourceforge.net>\fR
.PP
This manpage was created by \fBPICCORO Lenz McKAY\fR \fI<mckaygerhard@gmail.com>\fR for VenenuX development environment.
